version: "3.6"

services:

  monkeytype:
    container_name: monkeytype
    image: l4rm4nd/monkeytype:latest
    restart: on-failure
    volumes:
      - .:/app
    ports:
      - 127.0.0.1:8888:3000
      - 127.0.0.1:5005:5005

  monkeytype-redis:
    container_name: monkeytype-redis
    image: redis:6.2.6-alpine
    restart: on-failure
    expose:
      - 6379
    volumes:
      - ./redis-data:/data

  monkeytype-mongodb:
    container_name: monkeytype-mongodb
    image: mongo:5.0.8
    restart: on-failure
    expose:
      - 27017
    volumes:
      - ./mongo-data:/data/db
